version: '3'
services:
    moonbase:
        build: ./app
        environment:
            # MoonbaseOverseer API Key (Codea Forum Key)
            - DISCOURSE_API_KEY=
            - DISCOURSE_USERNAME=MoonbaseOverseer
            - DISCOURSE_WEBHOOK_SECRET=
            - HOST=moonbase.codea.io
            # 100MB
            - MAX_FILESIZE=104857600
        volumes:
            - ./app/repo:/app/repo:rw
        restart: always
