version: '3'
services:
    moonbase:
        build: ./app
        environment:
            # Moonbase Bot API Key (Codea Forum Key)
            - DISCOURSE_API_KEY=
        volumes:
            - ./app/repo:/app/repo:rw
        restart: always
