services:
    moonbase:
        build: .
        env_file:
            - .env
        volumes:
            - ./pb_public:/pb/pb_public
            - ./pb_migrations:/pb/pb_migrations
            - ./pb_data:/pb/pb_data
            - ./pb_hooks:/pb/pb_hooks
        restart: unless-stopped

networks:
    default:
        name: npm_internal
        external: true
